version: "3.9"
services:
  db:
    image: kartoza/postgis:13.0
    restart: always
    ports:
      - "54326:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASS: root
      POSTGRES_DB: books_management
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting,fuzzystrmatch
    volumes:
      - db_volume:/var/lib/postgresql
  python-api:
    depends_on:
      - db
    build: .
    shm_size: 256m
    ports:
      - "5000:5000"
    volumes:
      - .:/app/python-api
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://root:root@db:5432/books_management
volumes:
  db_volume:

